export const GUIDE_CATALOG = [
  {
    id: "administracion-alquileres",
    type: "manual",
    typeLabel: "Manual web",
    title: "Administración de Alquileres",
    description: "Contratos recurrentes y temporales, cobros, recibos, liquidaciones, cuentas de locadores y facturación ARCA.",
    audience: "Inmobiliarias y administradores",
    updatedLabel: "Septiembre de 2026",
    durationLabel: "12 min de lectura",
    icon: "🔑",
    to: "/guias/administracion-alquileres",
  },
  {
    id: "administracion-consorcios",
    type: "manual",
    typeLabel: "Manual web",
    title: "Administración de Consorcios",
    description: "Unidades, expensas, cobranzas, intereses, proveedores, tesorería, comunicaciones y cierre mensual.",
    audience: "Administradores de consorcios",
    updatedLabel: "Septiembre de 2026",
    durationLabel: "15 min de lectura",
    icon: "🏙️",
    to: "/guias/administracion-consorcios",
  },
  {
    id: "delegacion-arca",
    type: "guide",
    typeLabel: "Guía paso a paso",
    title: "Delegación de Facturación Electrónica",
    description: "Cómo delegar el servicio en ARCA y crear el punto de venta que utilizará ONO Prop.",
    audience: "Clientes que emitirán comprobantes",
    updatedLabel: "Agosto de 2026",
    durationLabel: "5 min de lectura",
    icon: "🧾",
    to: "/guias/delegacion-arca",
  },
];

